### ISSUE TITLE
can u please explain

### ISSUE THREAD

**Issue by jeevatrippy** [4unkur/laravel-video-chat#1]
hey there please explain me,
i done all things, when click on ids from chat room that shows only  two empty boxes only there is no "My caller id is" and there in no call buttons and user name in chat page i'm new to vue so please reply for me ... 

and why we return null values in this 
```
            return {
                id: null,
                users: [],
                room: null,
                caller: null,
                localUserMedia: null,
                channel: null,
                showEndCallButton: false,
                prepared: false,
                configuration: {
                    iceServers: [{
                        urls: 'stun:stun.l.google.com:19302'
                    }]
                }
            }
```
thanks in advance

**Comment by 4unkur** [comment]
Hi @jeevatrippy,

I coded this long time ago and didn't work with WebRTC recently, so I don't remember that much.  
But I suggest you check the console for the errors.  

> i done all things, when click on ids from chat room that shows only two empty boxes only there is no "My caller id is" and there in no call buttons and user name in chat page 

It means that WebRTC connection is not set.

> i'm new to vue 

There is nothing much about Vue

> and why we return null values in this

Because initially, you don't have those values, you set them after your peer to peer connection is set (it's already done in the code)

Note: Your website should be under HTTPS (requirement for WebRTC)

**Comment by jeevatrippy** [comment]
@4unkur thanks for your reply first 
How I set my WebRTC connection i put app key, I'd and secret details in .env from pusherjs  ,

And another one thing there is no errors in my console and then now I'm working in localhost only if it's working I'll push it into https server

**Comment by 4unkur** [comment]
Probably you are new to all this. You have to read a lot about WebRTC before going to production.  
I have googled a lot myself back then.

Some useful websites: https://bloggeek.me/ - a lot of info about WebRTC and all related stuff.  
Collection of WebRTC experiments:  https://github.com/muaz-khan/WebRTC-Experiment  
My code is based on the above experiments, I just converted it into Vue.

>  I'm working in localhost only

Even on localhost you have to use HTTPS. You can use Laravel Valet to enable HTTPS on localhost it's easy.

**Comment by jeevatrippy** [comment]
@4unkur thanks again 
Ok I'll read that above you mentioned  I'll try to fix this 😇😇 thanks for your support

**Comment by 4unkur** [comment]
You are welcome
